expose:
  type: ingress
  tls:
    enabled: true
    certSource: auto
    secret:
      secretName: harbor-tls
  ingress:
    hosts:
      core: harbor.apps.ocp.test2.com
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
externalURL: https://harbor.apps.ocp.test2.com:31455

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: local-storage
      size: 20Gi
    jobservice:
      jobLog:
        storageClass: local-storage
        accessMode: ReadWriteOnce
        size: 2Gi
    database:
      storageClass: local-storage
      accessMode: ReadWriteOnce
      size: 2Gi
    redis:
      storageClass: local-storage
      accessMode: ReadWriteOnce
      size: 2Gi
    trivy:
      storageClass: local-storage
      accessMode: ReadWriteOnce
      size: 5Gi

harborAdminPassword: "Harbor12345"
